name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
            arch: x64,arm64
          - os: windows-latest
            platform: win
            arch: x64,ia32
          - os: ubuntu-latest
            platform: linux
            arch: x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        # run: npm ci

      - name: Build React app
        run: npm run build

      - name: Build Electron app (macOS)
        if: startsWith(matrix.os, 'macos')
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Disable code signing
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Build Electron app (Windows)
        if: startsWith(matrix.os, 'windows')
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Disable code signing
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Build Electron app (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: dist/
          retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Display structure of downloaded files
        run: |
          echo "=== All artifacts ==="
          find ./artifacts -type f | sort
          echo "=== EXE files only ==="
          find ./artifacts -name "*.exe" -exec ls -la {} \;
          echo "=== AppImage files ==="
          find ./artifacts -name "*.AppImage" -exec ls -la {} \;
          echo "=== DEB files ==="
          find ./artifacts -name "*.deb" -exec ls -la {} \;
          echo "=== RPM files ==="
          find ./artifacts -name "*.rpm" -exec ls -la {} \;
          echo "=== Files to be uploaded ==="
          find ./artifacts -name "*-mac.zip" -o -name "*Setup*.exe" -o -name "*-1.*.exe" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" -o -name "latest*.yml"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/**/*-mac.zip
            ./artifacts/**/Azure*Setup*.exe
            ./artifacts/**/Azure*-1.*.exe
            ./artifacts/**/*.AppImage
            ./artifacts/**/*.deb
            ./artifacts/**/*.rpm
            ./artifacts/**/latest*.yml
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 