name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write
  actions: read

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Build Electron app (macOS)
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/
          retention-days: 30

  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Build Electron app (Windows)
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-build
          path: dist/
          retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Build Electron app (Linux)
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/
          retention-days: 30

  release:
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: |
          echo "=== All artifacts ==="
          find ./artifacts -type f | sort
          echo "=== EXE files only ==="
          find ./artifacts -name "*.exe" -exec ls -la {} \; || echo "No .exe files found"
          echo "=== AppImage files ==="
          find ./artifacts -name "*.AppImage" -exec ls -la {} \; || echo "No .AppImage files found"
          echo "=== DEB files ==="
          find ./artifacts -name "*.deb" -exec ls -la {} \; || echo "No .deb files found"
          echo "=== RPM files ==="
          find ./artifacts -name "*.rpm" -exec ls -la {} \; || echo "No .rpm files found"
          echo "=== MAC files ==="
          find ./artifacts -name "*-mac.zip" -exec ls -la {} \; || echo "No .zip files found"
          echo "=== Files to be uploaded ==="
          find ./artifacts -name "*-mac.zip" -o -name "*Setup*.exe" -o -name "*-1.*.exe" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" -o -name "latest*.yml" | sort

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/*-mac.zip
            ./artifacts/Azure*Setup*.exe
            ./artifacts/Azure*-1.*.exe
            ./artifacts/*.AppImage
            ./artifacts/*.deb
            ./artifacts/*.rpm
            ./artifacts/latest*.yml
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 